# Use root/example as user/password credentials
version: '3.1'

services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: boat
            MONGO_INITDB_ROOT_PASSWORD: 1q2w3e4r
        ports:
            - 27017:27017
