openapi: '3.0.1'
info:
    title: 'Boat Protector API'
    description: 'This is an API for boat protector system.'
    version: '1.0.0'
    contact:
        email: 'boat-protector@gmail.com'
servers:
    # id is subject to change
    - url: 'https://{domain}/{stage}'
      variables:
          id:
              default: 'test_domain'
          stage:
              default: 'dev'
tags:
    - name: boat
      description: 'Operations that involve basic boat info'
    - name: position
      description: "Operations that involve updating of boat's position"
    - name: emergency
      description: 'Operations that involve reporting boat emergency incident'
paths:
    /boats:
        get:
            tags:
                - boat
            summary: List all boats basic information.
            description: |
                For retrieving multiple boats's profile.
            operationId: listboats
            parameters:
                - in: query
                  name: location
                  required: false
                  description: Return boats in an area with this location as center
                  schema:
                      $ref: '#/components/schemas/location'
                - in: query
                  name: radius
                  required: false
                  description: Return boats in an area with this radius(Metre).
                  schema:
                      type: number
                      example: '10.2'

            responses:
                '200':
                    description: 'OK: List boats.'
                    content:
                        application/json:
                            schema:
                                required:
                                    - boats
                                properties:
                                    boats:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/boat'
        post:
            tags:
                - boat
            summary: Add boat to system.
            description: |
                For adding boat's profile to the system.
            operationId: postboat
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                boatName:
                                    type: string
                                    example: 'boom boat'
                                boatType:
                                    $ref: '#/components/schemas/boatType'
            responses:
                '201':
                    description: 'OK: Create boat.'
                    content:
                        application/json:
                            schema:
                                properties:
                                    boatID:
                                        type: string
                                        example: '1234'
    /boats/{boat-id}:
        parameters:
            - $ref: '#/components/parameters/boatID'
        get:
            tags:
                - boat
            summary: List specific boat basic information.
            description: |
                For retrieving boat's profile.
            operationId: getboat
            responses:
                '200':
                    description: 'OK: Get boat.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/boat'
    /boats/{boat-id}/position:
        parameters:
            - $ref: '#/components/parameters/boatID'
        patch:
            tags:
                - position
            summary: Update specific boat position
            description: |
                For updating boat's location
            operationId: patchboatPosition
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                timestamp:
                                    type: integer
                                    example: 12312323
                                latitude:
                                    type: number
                                    example: 03237.4587
                                longitude:
                                    type: number
                                    example: 03237.4587
            responses:
                '200':
                    $ref: '#/components/responses/200'
    /boats/{boat-id}/emergency:
        parameters:
            - $ref: '#/components/parameters/boatID'
        post:
            tags:
                - emergency
            summary: Reporting boat emergency
            description: |
                For reporting own boat emergency.
            operationId: postboatEmergency
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                timestamp:
                                    type: integer
                                    example: 12312323
                                latitude:
                                    type: number
                                    example: 03237.4587
                                longitude:
                                    type: number
                                    example: 03237.4587
                                emergencyType:
                                    $ref: '#/components/schemas/emergencyType'
            responses:
                '201':
                    description: 'OK: Create emergency report.'
                    content:
                        application/json:
                            schema:
                                properties:
                                    emergencyID:
                                        type: string
                                        example: '1234'
        patch:
            tags:
                - emergency
            summary: Cancelling boat emergency
            description: |
                For cancelling reported emergency.
            operationId: cancelboatEmergency
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                isCancelled:
                                    type: boolean
                                    example: true
            responses:
                '200':
                    $ref: '#/components/responses/200'

components:
    responses:
        200:
            description: 'Server return 200 OK response.'
            content:
                application/json:
                    schema:
                        properties:
                            code:
                                type: number
                                example: 200
                            message:
                                type: string
                                example: 'OK'
        201:
            description: 'Server return 201 created response.'
            content:
                application/json:
                    schema:
                        properties:
                            code:
                                type: number
                                example: 201
                            message:
                                type: string
                                example: 'resource created'
    parameters:
        boatID:
            in: path
            name: boat-id
            description: uniquely identifed boat
            schema:
                type: string
                example: '1234'
            required: true

    schemas:
        location:
            type: object
            properties:
                latitude:
                    type: number
                    example: 03237.4587
                longitude:
                    type: number
                    example: 03237.4587
        boatType:
            type: string
            enum: ['commercial', 'transport', 'personal']
            example: 'commercial'
        emergencyType:
            type: string
            enum: [SOS", 'sink']
            example: 'SOS'
        status:
            type: string
            enum: ['normal', 'SOS', 'sink']
            example: 'normal'
        boat:
            type: object
            properties:
                boatID:
                    type: string
                    example: '1234'
                boatName:
                    type: string
                    example: '1234'
                boatType:
                    $ref: '#/components/schemas/boatType'
                status:
                    $ref: '#/components/schemas/status'
                location:
                    $ref: '#/components/schemas/location'
